# Generated by Django 2.2.6 on 2020-02-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketscrumy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
