# Generated by Django 2.2.6 on 2020-02-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeremiahchukwuscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumyhistory',
            name='time_of_action',
            field=models.DateField(),
        ),
    ]
